"""empty message

Revision ID: 2551c7b3fdd1
Revises: 3adddbf51f97
Create Date: 2021-12-14 21:54:27.633757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2551c7b3fdd1'
down_revision = '3adddbf51f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hasil_tes', sa.Column('most_D', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('most_I', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('most_S', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('most_C', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('least_D', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('least_I', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('least_S', sa.Integer(), nullable=False))
    op.add_column('hasil_tes', sa.Column('least_C', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hasil_tes', 'least_C')
    op.drop_column('hasil_tes', 'least_S')
    op.drop_column('hasil_tes', 'least_I')
    op.drop_column('hasil_tes', 'least_D')
    op.drop_column('hasil_tes', 'most_C')
    op.drop_column('hasil_tes', 'most_S')
    op.drop_column('hasil_tes', 'most_I')
    op.drop_column('hasil_tes', 'most_D')
    # ### end Alembic commands ###
