"""empty message

Revision ID: 2fe973728b7a
Revises: 2ccb2b1c0cdd
Create Date: 2021-12-10 11:48:19.511983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fe973728b7a'
down_revision = '2ccb2b1c0cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=250), nullable=False))
    op.drop_column('user', 'nama')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nama', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
