"""empty message

Revision ID: 3adddbf51f97
Revises: dce92e636da9
Create Date: 2021-12-14 09:52:16.986677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adddbf51f97'
down_revision = 'dce92e636da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_tes',
    sa.Column('id_hasil', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('umur', sa.Integer(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=100), nullable=False),
    sa.Column('change_D', sa.Integer(), nullable=False),
    sa.Column('change_I', sa.Integer(), nullable=False),
    sa.Column('change_S', sa.Integer(), nullable=False),
    sa.Column('change_C', sa.Integer(), nullable=False),
    sa.Column('hasil_tipekepribadian', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_hasil')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil_tes')
    # ### end Alembic commands ###
