"""empty message

Revision ID: 441ee92f0d0c
Revises: 6544e01b8aa9
Create Date: 2021-12-17 11:33:37.928112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '441ee92f0d0c'
down_revision = '6544e01b8aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hasil_tes', 'hasil_tipekepribadian',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hasil_tes', 'hasil_tipekepribadian',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
