"""empty message

Revision ID: 560517d849ff
Revises: b5c5bb4638fe
Create Date: 2022-01-10 01:51:14.865990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560517d849ff'
down_revision = 'b5c5bb4638fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_tipekepribadian', sa.Column('rekomendasi_pekerjaan', sa.String(length=100000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_tipekepribadian', 'rekomendasi_pekerjaan')
    # ### end Alembic commands ###
