"""empty message

Revision ID: 6544e01b8aa9
Revises: 2551c7b3fdd1
Create Date: 2021-12-17 04:41:47.959028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6544e01b8aa9'
down_revision = '2551c7b3fdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphic__change',
    sa.Column('id_soal', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('change_d', sa.BigInteger(), nullable=True),
    sa.Column('change_i', sa.BigInteger(), nullable=True),
    sa.Column('change_s', sa.BigInteger(), nullable=True),
    sa.Column('change_c', sa.BigInteger(), nullable=True),
    sa.Column('skor', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id_soal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphic__change')
    # ### end Alembic commands ###
