"""empty message

Revision ID: 796d4ad373c8
Revises: d25e245d0056
Create Date: 2021-12-29 07:58:39.225920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796d4ad373c8'
down_revision = 'd25e245d0056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphic__least',
    sa.Column('id_soal', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('least_d', sa.Integer(), nullable=True),
    sa.Column('least_i', sa.Integer(), nullable=True),
    sa.Column('least_s', sa.Integer(), nullable=True),
    sa.Column('least_c', sa.Integer(), nullable=True),
    sa.Column('skor', sa.Float(), nullable=True),
    sa.Column('bagian', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_soal')
    )
    op.create_table('graphic__most',
    sa.Column('id_soal', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('most_d', sa.Integer(), nullable=True),
    sa.Column('most_i', sa.Integer(), nullable=True),
    sa.Column('most_s', sa.Integer(), nullable=True),
    sa.Column('most_c', sa.Integer(), nullable=True),
    sa.Column('skor', sa.Float(), nullable=True),
    sa.Column('bagian', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_soal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphic__most')
    op.drop_table('graphic__least')
    # ### end Alembic commands ###
