"""empty message

Revision ID: 83326d85bc15
Revises: b487dc743fca
Create Date: 2021-12-09 18:07:35.604060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83326d85bc15'
down_revision = 'b487dc743fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasiltes_jadi',
    sa.Column('id_hasiltes', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('most_d', sa.String(length=10), nullable=False),
    sa.Column('most_i', sa.String(length=10), nullable=False),
    sa.Column('most_s', sa.String(length=10), nullable=False),
    sa.Column('most_c', sa.String(length=10), nullable=False),
    sa.Column('least_d', sa.String(length=10), nullable=False),
    sa.Column('least_i', sa.String(length=10), nullable=False),
    sa.Column('least_s', sa.String(length=10), nullable=False),
    sa.Column('least_c', sa.String(length=10), nullable=False),
    sa.Column('change_d', sa.String(length=10), nullable=False),
    sa.Column('change_i', sa.String(length=10), nullable=False),
    sa.Column('change_s', sa.String(length=10), nullable=False),
    sa.Column('change_c', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_hasiltes')
    )
    op.create_table('user',
    sa.Column('id_user', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('hasiltes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasiltes',
    sa.Column('id_hasiltes', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('most_d', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('most_i', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('most_s', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('most_c', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_d', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_i', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_s', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_c', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_d', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_i', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_s', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_c', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_hasiltes'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('hasiltes_jadi')
    # ### end Alembic commands ###
