"""empty message

Revision ID: b487dc743fca
Revises: c7efc914096c
Create Date: 2021-12-09 09:22:10.199067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b487dc743fca'
down_revision = 'c7efc914096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasiltes',
    sa.Column('id_hasiltes', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('most_d', sa.String(length=10), nullable=False),
    sa.Column('most_i', sa.String(length=10), nullable=False),
    sa.Column('most_s', sa.String(length=10), nullable=False),
    sa.Column('most_c', sa.String(length=10), nullable=False),
    sa.Column('least_d', sa.String(length=10), nullable=False),
    sa.Column('least_i', sa.String(length=10), nullable=False),
    sa.Column('least_s', sa.String(length=10), nullable=False),
    sa.Column('least_c', sa.String(length=10), nullable=False),
    sa.Column('change_d', sa.String(length=10), nullable=False),
    sa.Column('change_i', sa.String(length=10), nullable=False),
    sa.Column('change_s', sa.String(length=10), nullable=False),
    sa.Column('change_c', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_hasiltes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasiltes')
    # ### end Alembic commands ###
