"""empty message

Revision ID: c7efc914096c
Revises: 1bd6978e408a
Create Date: 2021-12-07 17:18:12.367464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7efc914096c'
down_revision = '1bd6978e408a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soal',
    sa.Column('id_soal', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pernyataan_a', sa.String(length=1000), nullable=True),
    sa.Column('pernyataan_b', sa.String(length=1000), nullable=True),
    sa.Column('pernyataan_c', sa.String(length=1000), nullable=True),
    sa.Column('pernyataan_d', sa.String(length=1000), nullable=True),
    sa.Column('m_a', sa.String(length=10), nullable=False),
    sa.Column('m_b', sa.String(length=10), nullable=False),
    sa.Column('m_c', sa.String(length=10), nullable=False),
    sa.Column('m_d', sa.String(length=10), nullable=False),
    sa.Column('l_a', sa.String(length=10), nullable=False),
    sa.Column('l_b', sa.String(length=10), nullable=False),
    sa.Column('l_c', sa.String(length=10), nullable=False),
    sa.Column('l_d', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_soal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soal')
    # ### end Alembic commands ###
