"""empty message

Revision ID: d43ecb80ec40
Revises: 1fd421e6b82a
Create Date: 2022-01-09 19:37:24.948965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd43ecb80ec40'
down_revision = '1fd421e6b82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fix_dataset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fix_dataset',
    sa.Column('dominance', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('influance', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('steadiness', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('compliance', mysql.INTEGER(display_width=1), autoincrement=False, nullable=True),
    sa.Column('tipe_kepribadian', mysql.VARCHAR(length=31), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
