"""empty message

Revision ID: dce92e636da9
Revises: a525a584dbe1
Create Date: 2021-12-14 01:42:06.627284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dce92e636da9'
down_revision = 'a525a584dbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasiltes')
    op.add_column('user', sa.Column('image_file', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.create_table('hasiltes',
    sa.Column('id_hasiltes', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('most_d', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('most_i', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('most_s', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('most_c', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_d', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_i', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_s', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('least_c', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_d', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_i', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_s', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('change_c', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_hasiltes'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
