"""empty message

Revision ID: e8b68c3ee961
Revises: 441ee92f0d0c
Create Date: 2021-12-20 00:21:19.250424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b68c3ee961'
down_revision = '441ee92f0d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tipekepribadian',
    sa.Column('id_hasil', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipe_kepribadian', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_hasil')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_tipekepribadian')
    # ### end Alembic commands ###
