"""empty message

Revision ID: f6157d34c45e
Revises: e8b68c3ee961
Create Date: 2021-12-22 03:25:41.123733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6157d34c45e'
down_revision = 'e8b68c3ee961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graphic__change', 'bagian',
               existing_type=mysql.INTEGER(display_width=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graphic__change', 'bagian',
               existing_type=mysql.INTEGER(display_width=5),
               nullable=False)
    # ### end Alembic commands ###
